### PR TITLE
Add ensure newline at end of file command

### PR DESCRIPTION
**Pull request by dwt**
Since the remove whitespace is something I definitely cannot have, I created a new command that just ensures the newline at the end of file.

### CODE REVIEW

**Comment by dwt** [comment]
And created a pull request so other users of the plugin don't need to reinvent the wheel for this slight change.

**Comment by elia** [comment]
Can you make it check for the other ENV var to ensure the file doesn't get a double pass?

**Comment by dwt** [comment]
> Am 08.02.2016 um 21:07 schrieb Elia Schito <notifications@github.com>:
> 
> Can you make it check for the other ENV var to ensure the file doesn't get a double pass?
> 
I might be wrong, but the architecture of these filters seems to require that the content is passed through the filter anyway, so the only thing that would be optimised out by checking for the other env var would be `content << "\n" unless content.end_with? "\n“? which I can’t imagine to be slow.

Why do you see such a big performance gain in this?

If there is a bigger performance gain to be had by doing something clever with connecting stdin to stdout directly, then I fear my ruby isn’t strong enough to do that.

Best Regards,
Martin Häcker

**Comment by elia** [comment]
Yeah I'm aware of that and you're right, my concern was more about having a clear separation but that ought to be addressed by some architectural change anyway.

The only think missing for a merge is updating the readme adding instructions about the new ENV setting, it's enough to add them under the current trailing whitespace section.

(thanks for PR btw! 😀)

**Comment by dwt** [comment]
Like this?

**Comment by elia** [comment]
:wink: perfect

**Comment by dwt** [comment]
Thanks!

Considering this a bit more: maybe it would be easier to document and reason about these settings if `TM_STRIP_WHITESPACE_ON_SAVE` wouldn't actually append whitespace in a specific case?

This would probably need a deprecation period, but I guess it would certainly be cleaner.

**Comment by elia** [comment]
Agree on removing EOF newline from `TM_STRIP_WHITESPACE_ON_SAVE` and have separate routes for the two actions. I don't think there's a need for a deprecation period since you get that same behavior as before by default.

**Pull request merged**
